//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkLogForm.KjqbService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogInService", Namespace="http://schemas.datacontract.org/2004/07/KjqbService")]
    [System.SerializableAttribute()]
    public partial class LogInService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShareUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WriteUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShareUserId {
            get {
                return this.ShareUserIdField;
            }
            set {
                if ((this.ShareUserIdField.Equals(value) != true)) {
                    this.ShareUserIdField = value;
                    this.RaisePropertyChanged("ShareUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WriteUserId {
            get {
                return this.WriteUserIdField;
            }
            set {
                if ((this.WriteUserIdField.Equals(value) != true)) {
                    this.WriteUserIdField = value;
                    this.RaisePropertyChanged("WriteUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScheduleInService", Namespace="http://schemas.datacontract.org/2004/07/KjqbService")]
    [System.SerializableAttribute()]
    public partial class ScheduleInService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ScheduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ShareUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long WriteUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ScheduleId {
            get {
                return this.ScheduleIdField;
            }
            set {
                if ((this.ScheduleIdField.Equals(value) != true)) {
                    this.ScheduleIdField = value;
                    this.RaisePropertyChanged("ScheduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ShareUserId {
            get {
                return this.ShareUserIdField;
            }
            set {
                if ((this.ShareUserIdField.Equals(value) != true)) {
                    this.ShareUserIdField = value;
                    this.RaisePropertyChanged("ShareUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long WriteUserId {
            get {
                return this.WriteUserIdField;
            }
            set {
                if ((this.WriteUserIdField.Equals(value) != true)) {
                    this.WriteUserIdField = value;
                    this.RaisePropertyChanged("WriteUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentInService", Namespace="http://schemas.datacontract.org/2004/07/KjqbService")]
    [System.SerializableAttribute()]
    public partial class CommentInService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LogUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentUserName {
            get {
                return this.CommentUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentUserNameField, value) != true)) {
                    this.CommentUserNameField = value;
                    this.RaisePropertyChanged("CommentUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LogUserId {
            get {
                return this.LogUserIdField;
            }
            set {
                if ((this.LogUserIdField.Equals(value) != true)) {
                    this.LogUserIdField = value;
                    this.RaisePropertyChanged("LogUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeArrangeForManagerInService", Namespace="http://schemas.datacontract.org/2004/07/KjqbService")]
    [System.SerializableAttribute()]
    public partial class TimeArrangeForManagerInService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamineOrExamineresultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SendUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TimeArrangeForManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamineOrExamineresult {
            get {
                return this.ExamineOrExamineresultField;
            }
            set {
                if ((this.ExamineOrExamineresultField.Equals(value) != true)) {
                    this.ExamineOrExamineresultField = value;
                    this.RaisePropertyChanged("ExamineOrExamineresult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SendUserId {
            get {
                return this.SendUserIdField;
            }
            set {
                if ((this.SendUserIdField.Equals(value) != true)) {
                    this.SendUserIdField = value;
                    this.RaisePropertyChanged("SendUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TimeArrangeForManagerId {
            get {
                return this.TimeArrangeForManagerIdField;
            }
            set {
                if ((this.TimeArrangeForManagerIdField.Equals(value) != true)) {
                    this.TimeArrangeForManagerIdField = value;
                    this.RaisePropertyChanged("TimeArrangeForManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessService", Namespace="http://schemas.datacontract.org/2004/07/KjqbService")]
    [System.SerializableAttribute()]
    public partial class BusinessService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BusinessIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ReceiveIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BusinessID {
            get {
                return this.BusinessIDField;
            }
            set {
                if ((this.BusinessIDField.Equals(value) != true)) {
                    this.BusinessIDField = value;
                    this.RaisePropertyChanged("BusinessID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReceiveID {
            get {
                return this.ReceiveIDField;
            }
            set {
                if ((this.ReceiveIDField.Equals(value) != true)) {
                    this.ReceiveIDField = value;
                    this.RaisePropertyChanged("ReceiveID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaveInService", Namespace="http://schemas.datacontract.org/2004/07/KjqbService")]
    [System.SerializableAttribute()]
    public partial class LeaveInService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExamineOrExamineresultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LeaveIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SendUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExamineOrExamineresult {
            get {
                return this.ExamineOrExamineresultField;
            }
            set {
                if ((this.ExamineOrExamineresultField.Equals(value) != true)) {
                    this.ExamineOrExamineresultField = value;
                    this.RaisePropertyChanged("ExamineOrExamineresult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LeaveId {
            get {
                return this.LeaveIdField;
            }
            set {
                if ((this.LeaveIdField.Equals(value) != true)) {
                    this.LeaveIdField = value;
                    this.RaisePropertyChanged("LeaveId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SendUserId {
            get {
                return this.SendUserIdField;
            }
            set {
                if ((this.SendUserIdField.Equals(value) != true)) {
                    this.SendUserIdField = value;
                    this.RaisePropertyChanged("SendUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatInService", Namespace="http://schemas.datacontract.org/2004/07/KjqbService")]
    [System.SerializableAttribute()]
    public partial class ChatInService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChatContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ReceiveUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SendUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChatContent {
            get {
                return this.ChatContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatContentField, value) != true)) {
                    this.ChatContentField = value;
                    this.RaisePropertyChanged("ChatContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ReceiveUserId {
            get {
                return this.ReceiveUserIdField;
            }
            set {
                if ((this.ReceiveUserIdField.Equals(value) != true)) {
                    this.ReceiveUserIdField = value;
                    this.RaisePropertyChanged("ReceiveUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SendUserId {
            get {
                return this.SendUserIdField;
            }
            set {
                if ((this.SendUserIdField.Equals(value) != true)) {
                    this.SendUserIdField = value;
                    this.RaisePropertyChanged("SendUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KjqbService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInLogListInService", ReplyAction="http://tempuri.org/IService1/SaveInLogListInServiceResponse")]
        bool SaveInLogListInService(WorkLogForm.KjqbService.LogInService log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchShareLog", ReplyAction="http://tempuri.org/IService1/SearchShareLogResponse")]
        WorkLogForm.KjqbService.LogInService[] SearchShareLog(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetShareLogIsRead", ReplyAction="http://tempuri.org/IService1/SetShareLogIsReadResponse")]
        void SetShareLogIsRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchShareLogUnRead", ReplyAction="http://tempuri.org/IService1/SearchShareLogUnReadResponse")]
        WorkLogForm.KjqbService.LogInService[] SearchShareLogUnRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInScheduleListInService", ReplyAction="http://tempuri.org/IService1/SaveInScheduleListInServiceResponse")]
        bool SaveInScheduleListInService(WorkLogForm.KjqbService.ScheduleInService log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchShareSchedule", ReplyAction="http://tempuri.org/IService1/SearchShareScheduleResponse")]
        WorkLogForm.KjqbService.ScheduleInService[] SearchShareSchedule(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetShareScheduleIsRead", ReplyAction="http://tempuri.org/IService1/SetShareScheduleIsReadResponse")]
        void SetShareScheduleIsRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchShareScheduleUnRead", ReplyAction="http://tempuri.org/IService1/SearchShareScheduleUnReadResponse")]
        WorkLogForm.KjqbService.ScheduleInService[] SearchShareScheduleUnRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInCommentListInService", ReplyAction="http://tempuri.org/IService1/SaveInCommentListInServiceResponse")]
        bool SaveInCommentListInService(WorkLogForm.KjqbService.CommentInService log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchCommentlog", ReplyAction="http://tempuri.org/IService1/SearchCommentlogResponse")]
        WorkLogForm.KjqbService.CommentInService[] SearchCommentlog(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetCommentLogIsRead", ReplyAction="http://tempuri.org/IService1/SetCommentLogIsReadResponse")]
        void SetCommentLogIsRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchCommentlogUnRead", ReplyAction="http://tempuri.org/IService1/SearchCommentlogUnReadResponse")]
        WorkLogForm.KjqbService.CommentInService[] SearchCommentlogUnRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInTimeArrangeForManagerInService", ReplyAction="http://tempuri.org/IService1/SaveInTimeArrangeForManagerInServiceResponse")]
        bool SaveInTimeArrangeForManagerInService(WorkLogForm.KjqbService.TimeArrangeForManagerInService log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchTimeArrangeForManager", ReplyAction="http://tempuri.org/IService1/SearchTimeArrangeForManagerResponse")]
        WorkLogForm.KjqbService.TimeArrangeForManagerInService[] SearchTimeArrangeForManager(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTimeArrangeForManagerIsRead", ReplyAction="http://tempuri.org/IService1/SetTimeArrangeForManagerIsReadResponse")]
        void SetTimeArrangeForManagerIsRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchTimeArrangeForManagerUnRead", ReplyAction="http://tempuri.org/IService1/SearchTimeArrangeForManagerUnReadResponse")]
        WorkLogForm.KjqbService.TimeArrangeForManagerInService[] SearchTimeArrangeForManagerUnRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInBusinessListInService", ReplyAction="http://tempuri.org/IService1/SaveInBusinessListInServiceResponse")]
        bool SaveInBusinessListInService(WorkLogForm.KjqbService.BusinessService bs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchBusinessInfo", ReplyAction="http://tempuri.org/IService1/SearchBusinessInfoResponse")]
        WorkLogForm.KjqbService.BusinessService[] SearchBusinessInfo(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetBusinessInfoIsRead", ReplyAction="http://tempuri.org/IService1/SetBusinessInfoIsReadResponse")]
        void SetBusinessInfoIsRead(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchBusinessInfoUnRead", ReplyAction="http://tempuri.org/IService1/SearchBusinessInfoUnReadResponse")]
        WorkLogForm.KjqbService.BusinessService[] SearchBusinessInfoUnRead(long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInLeaveInfoInService", ReplyAction="http://tempuri.org/IService1/SaveInLeaveInfoInServiceResponse")]
        bool SaveInLeaveInfoInService(WorkLogForm.KjqbService.LeaveInService log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchLeaveInfo", ReplyAction="http://tempuri.org/IService1/SearchLeaveInfoResponse")]
        WorkLogForm.KjqbService.LeaveInService[] SearchLeaveInfo(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetLeaveInfoIsRead", ReplyAction="http://tempuri.org/IService1/SetLeaveInfoIsReadResponse")]
        void SetLeaveInfoIsRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchLeaveInfoUnRead", ReplyAction="http://tempuri.org/IService1/SearchLeaveInfoUnReadResponse")]
        WorkLogForm.KjqbService.LeaveInService[] SearchLeaveInfoUnRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServiceTime", ReplyAction="http://tempuri.org/IService1/GetServiceTimeResponse")]
        System.DateTime GetServiceTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInChatInfoInService", ReplyAction="http://tempuri.org/IService1/SaveInChatInfoInServiceResponse")]
        bool SaveInChatInfoInService(WorkLogForm.KjqbService.ChatInService chat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchChatInfo", ReplyAction="http://tempuri.org/IService1/SearchChatInfoResponse")]
        WorkLogForm.KjqbService.ChatInService[] SearchChatInfo(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetChatInfoIsRead", ReplyAction="http://tempuri.org/IService1/SetChatInfoIsReadResponse")]
        void SetChatInfoIsRead(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchChatInfoUnRead", ReplyAction="http://tempuri.org/IService1/SearchChatInfoUnReadResponse")]
        WorkLogForm.KjqbService.ChatInService[] SearchChatInfoUnRead(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WorkLogForm.KjqbService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WorkLogForm.KjqbService.IService1>, WorkLogForm.KjqbService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveInLogListInService(WorkLogForm.KjqbService.LogInService log) {
            return base.Channel.SaveInLogListInService(log);
        }
        
        public WorkLogForm.KjqbService.LogInService[] SearchShareLog(int Id) {
            return base.Channel.SearchShareLog(Id);
        }
        
        public void SetShareLogIsRead(int Id) {
            base.Channel.SetShareLogIsRead(Id);
        }
        
        public WorkLogForm.KjqbService.LogInService[] SearchShareLogUnRead(int Id) {
            return base.Channel.SearchShareLogUnRead(Id);
        }
        
        public bool SaveInScheduleListInService(WorkLogForm.KjqbService.ScheduleInService log) {
            return base.Channel.SaveInScheduleListInService(log);
        }
        
        public WorkLogForm.KjqbService.ScheduleInService[] SearchShareSchedule(int Id) {
            return base.Channel.SearchShareSchedule(Id);
        }
        
        public void SetShareScheduleIsRead(int Id) {
            base.Channel.SetShareScheduleIsRead(Id);
        }
        
        public WorkLogForm.KjqbService.ScheduleInService[] SearchShareScheduleUnRead(int Id) {
            return base.Channel.SearchShareScheduleUnRead(Id);
        }
        
        public bool SaveInCommentListInService(WorkLogForm.KjqbService.CommentInService log) {
            return base.Channel.SaveInCommentListInService(log);
        }
        
        public WorkLogForm.KjqbService.CommentInService[] SearchCommentlog(int Id) {
            return base.Channel.SearchCommentlog(Id);
        }
        
        public void SetCommentLogIsRead(int Id) {
            base.Channel.SetCommentLogIsRead(Id);
        }
        
        public WorkLogForm.KjqbService.CommentInService[] SearchCommentlogUnRead(int Id) {
            return base.Channel.SearchCommentlogUnRead(Id);
        }
        
        public bool SaveInTimeArrangeForManagerInService(WorkLogForm.KjqbService.TimeArrangeForManagerInService log) {
            return base.Channel.SaveInTimeArrangeForManagerInService(log);
        }
        
        public WorkLogForm.KjqbService.TimeArrangeForManagerInService[] SearchTimeArrangeForManager(int Id) {
            return base.Channel.SearchTimeArrangeForManager(Id);
        }
        
        public void SetTimeArrangeForManagerIsRead(int Id) {
            base.Channel.SetTimeArrangeForManagerIsRead(Id);
        }
        
        public WorkLogForm.KjqbService.TimeArrangeForManagerInService[] SearchTimeArrangeForManagerUnRead(int Id) {
            return base.Channel.SearchTimeArrangeForManagerUnRead(Id);
        }
        
        public bool SaveInBusinessListInService(WorkLogForm.KjqbService.BusinessService bs) {
            return base.Channel.SaveInBusinessListInService(bs);
        }
        
        public WorkLogForm.KjqbService.BusinessService[] SearchBusinessInfo(long Id) {
            return base.Channel.SearchBusinessInfo(Id);
        }
        
        public void SetBusinessInfoIsRead(long Id) {
            base.Channel.SetBusinessInfoIsRead(Id);
        }
        
        public WorkLogForm.KjqbService.BusinessService[] SearchBusinessInfoUnRead(long Id) {
            return base.Channel.SearchBusinessInfoUnRead(Id);
        }
        
        public bool SaveInLeaveInfoInService(WorkLogForm.KjqbService.LeaveInService log) {
            return base.Channel.SaveInLeaveInfoInService(log);
        }
        
        public WorkLogForm.KjqbService.LeaveInService[] SearchLeaveInfo(int Id) {
            return base.Channel.SearchLeaveInfo(Id);
        }
        
        public void SetLeaveInfoIsRead(int Id) {
            base.Channel.SetLeaveInfoIsRead(Id);
        }
        
        public WorkLogForm.KjqbService.LeaveInService[] SearchLeaveInfoUnRead(int Id) {
            return base.Channel.SearchLeaveInfoUnRead(Id);
        }
        
        public System.DateTime GetServiceTime() {
            return base.Channel.GetServiceTime();
        }
        
        public bool SaveInChatInfoInService(WorkLogForm.KjqbService.ChatInService chat) {
            return base.Channel.SaveInChatInfoInService(chat);
        }
        
        public WorkLogForm.KjqbService.ChatInService[] SearchChatInfo(int Id) {
            return base.Channel.SearchChatInfo(Id);
        }
        
        public void SetChatInfoIsRead(int Id) {
            base.Channel.SetChatInfoIsRead(Id);
        }
        
        public WorkLogForm.KjqbService.ChatInService[] SearchChatInfoUnRead(int Id) {
            return base.Channel.SearchChatInfoUnRead(Id);
        }
    }
}
